yarnPath: .yarn/releases/yarn-3.2.3.cjs
npmRegistryServer: 'http://__RegistryServer__/__NexusNPMProxy__/'
enableStrictSsl: false
nodeLinker: node-modules
unsafeHttpWhitelist:
  - registry.ural.evraz.com
  - sib-reg-001.sib.evraz.com
