import {
	CHANNEL_NUMBER_FILTER_INDEX,
	DEVICE_NAME_FILTER_INDEX,
	DEVICE_NUMBER_FILTER_INDEX,
	GROUP_EWORK_FILTER_INDEX,
	GROUP_NAME_FILTER_INDEX,
	GROUP_NUMBER_FILTER_INDEX,
} from '../Const';

export type FiltersTypes =
	| typeof GROUP_NUMBER_FILTER_INDEX
	| typeof GROUP_NAME_FILTER_INDEX
	| typeof GROUP_EWORK_FILTER_INDEX
	| typeof DEVICE_NUMBER_FILTER_INDEX
	| typeof DEVICE_NAME_FILTER_INDEX
	| typeof CHANNEL_NUMBER_FILTER_INDEX;
