export const PARAMETERS_MODAL_TYPE = [
	'groupId',
	'csqlGroupName',
	'asqlGroupId',
	'asqlGroupName',
	'csqlChannel',
	'metricId',
	'metricName',
	'groupName',
	'd1GroupNumber',
	'd2GroupNumber',
	'd3GroupNumber',
	'dg1GroupNumber',
	'dg2GroupNumber',
	'statusGroupNumber',
	'ind_statname',
	'ind_d1name',
	'ind_d2name',
	'ind_d3name',
	'ind_dg1name',
	'ind_dg2name',
];
export const PARAMETERS_GROUP_TYPE = [
	'groupId',
	'csqlGroupName',
	'asqlGroupName',
	'asqlGroupId',
	'groupName',
	'd1GroupNumber',
	'd2GroupNumber',
	'd3GroupNumber',
	'dg1GroupNumber',
	'dg2GroupNumber',
	'statusGroupNumber',
];
export const STATUS_INDICATOR_COLOR_PARAMETERS = [
	'normalIndicatorColor',
	'emergencyIndicatorColor',
	'warningIndicatorColor',
	'turnedOffIndicatorColor',
	'errorIndicatorColor',
];
export const STATUS_INDICATOR_DEFAULT_COLORS = {
	normalIndicatorColor: '#92BC8C',
	emergencyIndicatorColor: '#E04621',
	warningIndicatorColor: '#FDD58B',
	turnedOffIndicatorColor: '#DECCDB',
	errorIndicatorColor: '#B1B1B2',
};
