enableStrictSsl: false

nodeLinker: node-modules

npmRegistryServer: "http://registry.ural.evraz.com/repository/ural_npm_group/"

unsafeHttpWhitelist:
  - registry.ural.evraz.com

yarnPath: .yarn/releases/yarn-3.2.3.cjs
